---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=1.6
  - ANSIBLE_VERSION=1.7
  - ANSIBLE_VERSION=1.8
#  - ANSIBLE_VERSION=1.9 -- why is this broken? Vagrant on Valkyrie wants Ansible 1.9
  - ANSIBLE_VERSION=2.0
  - ANSIBLE_VERSION=2.0.0.1


# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
