---
# tasks file for ansible-role-drulenium
- name: Ensure Drulenium dependencies are installed.
  apt:
    pkg: '{{ item }}'
    state: 'latest'
    install_recommends: no
  with_items:
    - '{{ drulenium_dependencies }}'
  register: drulenium_dependencies_install_status
  changed_when: drulenium_dependencies_install_status.stdout.find("0 upgraded, 0 newly installed, 0 to remove") == -1

- debug:
    var: drulenium_dependencies_install_status

- name: Ensure Drulenium additional dependencies are installed.
  apt:
    pkg: '{{ item }}'
    state: 'latest'
    install_recommends: yes
  with_items:
    - '{{ drulenium_additional_packages }}'
  register: drulenium_additional_packages_status

- debug:
    var: drulenium_additional_packages_status
