---
# tasks file for ansible-role-drulenium
#- name: Ensure Drulenium dependencies are installed.
#  apt:
#    name: "{{ item }}"
#    state: present
#  when: (drulenium_manage_dependencies == true) and (ansible_os_family == 'Debian')
#  with_items: drulenium_dependencies
#  register: drulenium_dependencies_install_status

#- name: Install additional packages.
#  apt:
#    name: "{{ item }}"
#    state: present
#  when: (drulenium_install_additional_packages == true) and (ansible_os_family == 'Debian')
#  with_items: drulenium_additional_packages

 - apt: name=imagemagick state=present install_recommends=true
